config:
  selfUrl: # https://saas.microservicesolution.dev
  corsOrigins: https://microservicesolution-st-gateway-web,https://microservicesolution-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://microservicesolution-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.microservicesolution.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.microservicesolution.dev
  tlsSecret: microservicesolution-tls

image:
  repository: mycompanyname/microservicesolution-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      